import { ArrowDown, CheckCircle2 } from 'lucide-react';
import { useState } from 'react';

const capabilities = [
  { name: 'Cyber Strategy & GRC', can: ['Establish governance and operating models', 'Clarify ownership and accountability', 'Build strategies, policies and roadmaps'], problems: 'Fragmented security activity, unclear accountability and reporting that does not support decisions.', activities: ['Stakeholder discovery', 'Maturity assessment', 'Control and RACI design', 'KPI/KRI definition'], deliverables: ['Governance model', 'Cybersecurity strategy', 'Control catalogue', 'Executive dashboard'], frameworks: ['ISO 27001', 'NIST CSF 2.0', 'COBIT'], value: 'A structured, accountable and measurable security programme.' },
  { name: 'Frameworks & Compliance', can: ['Interpret requirements', 'Map and tailor controls', 'Define audit-ready evidence'], problems: 'Overlapping obligations, unclear applicability and last-minute audit preparation.', activities: ['Gap assessment', 'Control mapping', 'Evidence review', 'Remediation monitoring'], deliverables: ['Control matrix', 'Gap assessment', 'Evidence pack', 'Audit readiness report'], frameworks: ['ISO 27001', 'PCI DSS', 'SOC 2', 'NIST SP 800-53'], value: 'Defensible compliance that supports the business rather than checklist completion.' },
  { name: 'Risk & Assurance', can: ['Assess inherent and residual risk', 'Review control effectiveness', 'Structure treatment and acceptance'], problems: 'Poor risk visibility, inconsistent scoring and remediation without clear priorities.', activities: ['Identify', 'Analyse', 'Evaluate', 'Treat', 'Monitor', 'Report'], deliverables: ['Risk register', 'Treatment plan', 'Assurance review', 'Risk acceptance'], frameworks: ['NIST RMF', 'ISO 27005', 'NIST CSF 2.0'], value: 'Investment and remediation decisions grounded in meaningful business risk.' },
  { name: 'IAM & Privacy', can: ['Design IAM governance', 'Assess access and privilege controls', 'Embed privacy and secure-by-design'], problems: 'Excessive access, unclear identity ownership and privacy risks introduced through change.', activities: ['Access review design', 'SoD analysis', 'PAM assurance', 'Privacy control review'], deliverables: ['IAM governance review', 'Access control matrix', 'Risk report', 'Remediation plan'], frameworks: ['ISO 27001', 'NIST SP 800-53', 'Privacy by Design'], value: 'Trusted access with clear accountability and reduced identity-driven exposure.' },
  { name: 'Operational Resilience', can: ['Establish BCP/DR governance', 'Plan and facilitate exercises', 'Validate corrective action'], problems: 'Plans that are untested, unclear recovery ownership and weak post-exercise follow-through.', activities: ['Prepare', 'Exercise', 'Observe', 'Identify gaps', 'Remediate', 'Validate'], deliverables: ['BCP/DR assessment', 'Exercise report', 'Issue tracker', 'Readiness dashboard'], frameworks: ['ISO 22301', 'NIST CSF', 'Operational resilience guidance'], value: 'Critical services that can withstand, respond to and recover from disruption.' },
  { name: 'AI Security & Governance', can: ['Govern AI use cases and agents', 'Assess data, model and supply-chain risk', 'Design oversight and assurance'], problems: 'Uncontrolled adoption, unclear accountability and inadequate monitoring of AI risks.', activities: ['Use case intake', 'Threat modelling', 'Control integration', 'Human oversight design'], deliverables: ['AI governance model', 'AI risk assessment', 'Acceptable-use controls', 'Assurance plan'], frameworks: ['NIST AI RMF', 'NIST CSF 2.0', 'ISO/IEC 42001'], value: 'Responsible, secure AI adoption with proportionate controls and visible risk.' },
];

const challenges = [
  ['Framework Alignment & Maturity', ['Understand business context', 'Define scope', 'Assess current state', 'Tailor controls', 'Identify gaps & risks', 'Build the roadmap', 'Implement', 'Validate evidence', 'Measure & improve'], ['NIST CSF 2.0', 'NIST SP 800-53', 'NIST RMF'], ['Current & Target Profiles', 'Control matrix', 'Risk register', 'Remediation roadmap']],
  ['Assurance & Regulatory Compliance', ['Confirm criteria', 'Set evidence plan', 'Test control design', 'Validate operation', 'Close priority gaps', 'Run readiness review'], ['ISO 27001', 'PCI DSS', 'SOC 2'], ['Evidence pack', 'Gap assessment', 'Audit readiness report']],
  ["Enterprise Risk Visibility", ['Set context', 'Identify scenarios', 'Analyse impact', 'Evaluate controls', 'Prioritise treatment', 'Report decisions'], ['NIST RMF', 'ISO 27005'], ['Risk register', 'Treatment plan', 'Executive dashboard']],
  ['Identity Transformation', ['Map identities', 'Define ownership', 'Assess access lifecycle', 'Review privilege & SoD', 'Prioritise controls', 'Monitor'], ['NIST SP 800-53', 'ISO 27001'], ['IAM governance review', 'RACI', 'Control matrix']],
  ['Operational Resilience', ['Identify critical services', 'Set recovery objectives', 'Assess plans', 'Exercise', 'Remediate', 'Validate'], ['ISO 22301', 'NIST CSF'], ['BCP/DR assessment', 'Exercise report', 'Action tracker']],
  ['Secure AI Governance', ['Qualify use case', 'Assess data & model', 'Threat model', 'Select controls', 'Define oversight', 'Monitor & assure'], ['NIST AI RMF', 'ISO/IEC 42001'], ['AI risk assessment', 'Governance model', 'Assurance plan']],
] as const;

const flow = [
  ['Framework / Regulation', 'Interpret the external obligation in its business and risk context.'], ['Requirement', 'Translate regulatory, contractual and security expectations into clear organisational requirements.'], ['Control', 'Turn requirements into practical governance, process and technical controls with ownership.'], ['Evidence', 'Define what proves each control exists and operates effectively.'], ['Risk', 'Translate weaknesses into meaningful business risk and decision context.'], ['Remediation', 'Define proportionate actions, priorities, owners and deadlines.'], ['Management Decision', 'Give leaders the information to invest, remediate or accept risk.'],
] as const;
const deliverables = ['Cybersecurity Strategy', 'Governance Framework', 'Risk Register', 'Control Matrix', 'Gap Assessment', 'Compliance Assessment', 'NIST Current Profile', 'NIST Target Profile', 'Cybersecurity Roadmap', 'Policies and Procedures', 'Evidence Pack', 'Audit Readiness Assessment', 'Remediation Plan', 'Executive Dashboard', 'KPI/KRI Report', 'BCP/DR Assessment', 'IAM Governance Review', 'AI Risk Assessment'];
const frameworkUses: Record<string, string> = { 'ISO 27001': 'Build and assure a risk-based information security management system.', 'PCI DSS': 'Protect payment data through scoped, testable security requirements.', 'SOC 2': 'Demonstrate trusted service controls through evidence and assurance.', 'NIST CSF': 'Describe current and target cybersecurity outcomes in business language.', 'NIST SP 800-53': 'Select and assess a comprehensive catalogue of security controls.', 'NIST RMF': 'Connect categorisation, control selection, assessment and ongoing risk decisions.', 'NIST AI RMF': 'Govern and manage trustworthiness risks throughout the AI lifecycle.' };

export function AboutX1Page() {
  const [capability, setCapability] = useState(0); const [challenge, setChallenge] = useState(0); const [stage, setStage] = useState(0); const [delivery, setDelivery] = useState(0); const [framework, setFramework] = useState('ISO 27001');
  const selected = capabilities[capability]; const selectedChallenge = challenges[challenge];
  return <section className="capability-page space-y-8">
    <header className="capability-hero glass rounded-3xl p-6 md:p-10"><p className="academic-eyebrow">Cybersecurity capability portfolio</p><h1 className="mt-3 max-w-5xl text-3xl font-semibold leading-tight md:text-5xl">Securing the Enterprise. Enabling the Business.</h1><p className="mt-5 max-w-4xl text-base leading-7 text-muted">I translate complex regulatory, cyber-risk and technology requirements into defensible governance, practical controls and measurable security improvement—connecting technical reality with business priorities, clearer risk decisions and resilient operating models.</p><a className="academic-primary mt-6 inline-flex" href="#capabilities">Explore My Capabilities</a></header>

    <section id="capabilities" aria-labelledby="capabilities-title"><p className="academic-eyebrow">Strategic cybersecurity advisory</p><h2 id="capabilities-title" className="mt-2 text-3xl font-semibold">Capability explorer</h2><div className="capability-tabs mt-5" role="tablist" aria-label="Cybersecurity capabilities">{capabilities.map((item, index) => <button role="tab" aria-selected={capability === index} className={capability === index ? 'is-active' : ''} onClick={() => setCapability(index)} key={item.name}>{item.name}</button>)}</div><article className="glass mt-4 rounded-2xl p-5 md:p-7" role="tabpanel"><h3 className="text-2xl font-semibold">{selected.name}</h3><div className="mt-5 grid gap-6 md:grid-cols-2 lg:grid-cols-3"><Info title="Strategic objective" items={selected.can} /><Info title="How I create value" text={selected.problems} /><Info title="Typical interventions" items={selected.activities} /><Info title="Deliverables" items={selected.deliverables} /><Info title="Relevant frameworks" items={selected.frameworks} /><Info title="Business outcome" text={selected.value} /></div></article></section>

    <section aria-labelledby="challenge-title"><p className="academic-eyebrow">Strategic scenarios &amp; solutions</p><h2 id="challenge-title" className="mt-2 text-3xl font-semibold">Addressing Strategic Cybersecurity Imperatives</h2><div className="challenge-layout mt-5"><div className="capability-tabs vertical" role="list">{challenges.map((item, index) => <button className={challenge === index ? 'is-active' : ''} onClick={() => setChallenge(index)} key={item[0]}>{item[0]}</button>)}</div><article className="glass rounded-2xl p-5"><h3 className="text-xl font-semibold">{selectedChallenge[0]}</h3><div className="journey mt-5">{selectedChallenge[1].map((step, index) => <div key={step}><span>{index + 1}</span><p>{step}</p>{index < selectedChallenge[1].length - 1 && <ArrowDown size={15} aria-hidden="true" />}</div>)}</div><div className="mt-5 grid gap-4 sm:grid-cols-2"><Info title="Relevant frameworks" items={[...selectedChallenge[2]]} /><Info title="Potential outputs" items={[...selectedChallenge[3]]} /></div><div className="mt-5 border-t border-white/10 pt-5"><Info title="Leadership value" text="Creates traceability between business expectations, controls, evidence, risk and investment priorities." /></div></article></div></section>

    <section aria-labelledby="reality-title"><p className="academic-eyebrow">Requirement to reality</p><h2 id="reality-title" className="mt-2 text-3xl font-semibold">From obligation to management decision</h2><div className="flow-nodes mt-5">{flow.map((item, index) => <button key={item[0]} onClick={() => setStage(index)} className={stage === index ? 'is-active' : ''}>{item[0]}</button>)}</div><div className="glass mt-3 rounded-2xl p-5" aria-live="polite"><h3 className="text-xl font-semibold">{flow[stage][0]}</h3><p className="mt-2 text-muted">{flow[stage][1]}</p></div></section>

    <section aria-labelledby="delivery-title"><p className="academic-eyebrow">What I deliver</p><h2 id="delivery-title" className="mt-2 text-3xl font-semibold">Decision-ready security artefacts</h2><div className="deliverable-grid mt-5">{deliverables.map((item, index) => <button key={item} className={delivery === index ? 'is-active' : ''} onClick={() => setDelivery(index)}>{item}</button>)}</div><article className="glass mt-4 grid gap-5 rounded-2xl p-5 md:grid-cols-3"><Info title="Purpose" text={`Create a clear, usable ${deliverables[delivery].toLowerCase()} aligned to scope and risk.`} /><Info title="Typical content" text="Context, scope, ownership, analysis, evidence, priorities and measurable next actions." /><Info title="Business outcome" text="A defensible basis for action, assurance, investment and executive decision-making." /></article></section>

    <section aria-labelledby="framework-title"><p className="academic-eyebrow">Framework knowledge map</p><h2 id="framework-title" className="mt-2 text-3xl font-semibold">Cybersecurity Governance &amp; Risk</h2><div className="framework-map mt-5"><div className="framework-core">Cybersecurity<br />Governance &amp; Risk</div><div className="framework-orbit">{Object.keys(frameworkUses).map((item) => <button className={framework === item ? 'is-active' : ''} onClick={() => setFramework(item)} key={item}>{item}</button>)}</div></div><p className="glass mt-3 rounded-2xl p-5 text-muted" aria-live="polite"><strong className="text-current">{framework}:</strong> {frameworkUses[framework]}</p></section>

    <section aria-labelledby="principles-title"><p className="academic-eyebrow">How I think</p><h2 id="principles-title" className="mt-2 text-3xl font-semibold">Consulting principles</h2><div className="mt-5 grid gap-3">{[['Business First', 'Understand business context, services and stakeholders before selecting controls.'], ['Risk-Based', 'Prioritise cybersecurity according to risk rather than checklist completion.'], ['Evidence-Driven', 'A control should be demonstrable and defensible.'], ['Practical', 'Translate complex standards into implementable actions.'], ['Executive-Ready', 'Convert technical issues into business impact, ownership, deadlines and decisions.']].map(([title, text]) => <details className="glass principle rounded-xl" key={title}><summary>{title}</summary><p>{text}</p></details>)}</div></section>
  </section>;
}

function Info({ title, items, text }: { title: string; items?: string[]; text?: string }) { return <div><h4 className="text-sm font-semibold uppercase tracking-wider">{title}</h4>{items ? <ul className="mt-2 space-y-2 text-sm text-muted">{items.map((item) => <li className="flex gap-2" key={item}><CheckCircle2 size={15} className="mt-1 shrink-0" aria-hidden="true" />{item}</li>)}</ul> : <p className="mt-2 text-sm leading-6 text-muted">{text}</p>}</div>; }
