import { ContentItem } from './types';

const paragraph = `In a modern digital environment, resilient systems are designed with layered controls, clear ownership, and continuous visibility. Teams that succeed are the ones who pair strategic architecture with practical day-to-day execution.`;

export const content: ContentItem[] = [
  {
    title: 'Zero Trust in Practice: Building Verifiable Access', slug: 'zero-trust-practice', description: 'How to operationalize least privilege and continuous verification.', date: '2026-01-12', category: 'Zero Trust', tags: ['zero-trust', 'iam', 'architecture'], readingTime: '9 min', featured: true, cover: 'from-cyan-500/30 to-blue-500/20', kind: 'blog', universe: 'professional', body: `${paragraph}\n\n### Key Principles\n- Never trust, always verify\n- Context-driven authentication\n- Micro-segmented blast radius\n\n\`\`\`bash\n# Example policy validation command\nopa eval --data policy.rego --input request.json 'data.authz.allow'\n\`\`\`\n\n> Callout: Start with identity hardening before network micro-segmentation.`
  },
  { title: 'Cloud Security Fundamentals for Modern Teams', slug: 'cloud-security-fundamentals', description: 'A pragmatic baseline for cloud-first organizations.', date: '2025-12-02', category: 'Cloud Security', tags: ['cloud', 'cnapp', 'governance'], readingTime: '7 min', cover: 'from-indigo-500/30 to-slate-500/20', kind: 'blog', universe: 'professional', body: `${paragraph}\n\n### Controls\nInventory, posture management, and automated remediation close the loop.` },
  { title: 'Identity and Access Management at Scale', slug: 'iam-at-scale', description: 'Blueprints for scalable IAM and secure onboarding.', date: '2025-11-03', category: 'Identity', tags: ['iam', 'sso', 'access-control'], readingTime: '8 min', cover: 'from-emerald-500/30 to-cyan-500/20', kind: 'blog', universe: 'professional', body: `${paragraph}\n\n### What Good Looks Like\nCentralized identity, role mapping, and periodic recertification.` },
  { title: 'Vulnerability Management That Actually Reduces Risk', slug: 'vulnerability-management', description: 'Prioritization models tied to business impact.', date: '2025-10-11', category: 'Vulnerability Management', tags: ['cve', 'prioritization', 'risk'], readingTime: '6 min', cover: 'from-amber-500/25 to-red-500/20', kind: 'blog', universe: 'professional', body: `${paragraph}` },
  { title: 'Security Architecture Principles for Product Teams', slug: 'security-architecture-principles', description: 'Embedding security architecture into product velocity.', date: '2025-09-19', category: 'Security Architecture', tags: ['architecture', 'threat-modeling', 'sdlc'], readingTime: '10 min', cover: 'from-fuchsia-500/30 to-violet-500/20', kind: 'blog', universe: 'professional', body: `${paragraph}` },
  { title: 'SOC & Detection Engineering Starter Blueprint', slug: 'soc-detection-engineering', description: 'Use case driven detection engineering for mature SOCs.', date: '2025-08-22', category: 'Detection Engineering', tags: ['soc', 'siem', 'detections'], readingTime: '11 min', cover: 'from-sky-500/30 to-indigo-500/20', kind: 'blog', universe: 'professional', body: `${paragraph}` },

  { title: 'Atomic Habits — Systems Over Goals', slug: 'atomic-habits-summary', description: 'Summary and key frameworks from Atomic Habits.', date: '2026-01-06', category: 'Books', tags: ['habits', 'productivity'], readingTime: '5 min', featured: true, cover: 'from-violet-500/35 to-purple-500/20', kind: 'book-summary', universe: 'personal', body: `${paragraph}` },
  { title: 'Deep Work — Focus as a Competitive Advantage', slug: 'deep-work-summary', description: 'A practical lens on focus in distracted environments.', date: '2025-12-08', category: 'Books', tags: ['focus', 'career'], readingTime: '6 min', cover: 'from-purple-500/35 to-indigo-500/20', kind: 'book-summary', universe: 'personal', body: `${paragraph}` },
  { title: 'The Psychology of Money — Behavior > Intelligence', slug: 'psychology-of-money-summary', description: 'Lessons on risk, patience, and decision quality.', date: '2025-11-12', category: 'Books', tags: ['finance', 'mindset'], readingTime: '5 min', cover: 'from-pink-500/30 to-purple-500/20', kind: 'book-summary', universe: 'personal', body: `${paragraph}` },
  { title: 'The Almanack of Naval Ravikant — Leverage & Clarity', slug: 'almanack-summary', description: 'A distilled set of ideas around wealth and happiness.', date: '2025-10-01', category: 'Books', tags: ['leverage', 'philosophy'], readingTime: '5 min', cover: 'from-indigo-500/30 to-violet-500/20', kind: 'book-summary', universe: 'personal', body: `${paragraph}` },

  { title: 'Attack on Titan — Freedom, Cycles, and Cost', slug: 'aot-summary', description: 'Themes, arcs, and worldbuilding highlights.', date: '2025-12-22', category: 'Anime', tags: ['dark-fantasy', 'strategy'], readingTime: '6 min', cover: 'from-red-500/30 to-violet-500/20', kind: 'anime-summary', universe: 'personal', body: `${paragraph}` },
  { title: 'Steins;Gate — Time, Sacrifice, and Choice', slug: 'steins-gate-summary', description: 'Narrative craft in one of sci-fi anime’s best stories.', date: '2025-11-30', category: 'Anime', tags: ['sci-fi', 'time-travel'], readingTime: '5 min', cover: 'from-cyan-500/30 to-purple-500/20', kind: 'anime-summary', universe: 'personal', body: `${paragraph}` },
  { title: 'Vinland Saga — Violence, Meaning, and Growth', slug: 'vinland-saga-summary', description: 'Character evolution and moral architecture.', date: '2025-10-24', category: 'Anime', tags: ['historical', 'character'], readingTime: '7 min', cover: 'from-orange-500/30 to-violet-500/20', kind: 'anime-summary', universe: 'personal', body: `${paragraph}` },
  { title: 'Frieren — Memory and the Long Arc of Time', slug: 'frieren-summary', description: 'A calm emotional epic with beautiful pacing.', date: '2025-09-08', category: 'Anime', tags: ['fantasy', 'emotional'], readingTime: '4 min', cover: 'from-teal-500/30 to-indigo-500/20', kind: 'anime-summary', universe: 'personal', body: `${paragraph}` },

  { title: 'Breaking Bad — Transformation and Consequence', slug: 'breaking-bad-summary', description: 'How tension and character logic create a masterpiece.', date: '2025-11-09', category: 'Series', tags: ['drama', 'character-arc'], readingTime: '6 min', cover: 'from-emerald-500/30 to-slate-500/20', kind: 'series-summary', universe: 'personal', body: `${paragraph}` },
  { title: 'Dark — Narrative Complexity Done Right', slug: 'dark-summary', description: 'A series summary focused on structure and payoff.', date: '2025-10-14', category: 'Series', tags: ['sci-fi', 'mystery'], readingTime: '6 min', cover: 'from-blue-500/30 to-violet-500/20', kind: 'series-summary', universe: 'personal', body: `${paragraph}` },
  { title: 'Severance — Identity in Corporate Systems', slug: 'severance-summary', description: 'Sharp design, satire, and psychological depth.', date: '2025-09-22', category: 'Series', tags: ['psychology', 'corporate'], readingTime: '5 min', cover: 'from-cyan-500/30 to-indigo-500/20', kind: 'series-summary', universe: 'personal', body: `${paragraph}` },
  { title: 'Arcane — Visual Storytelling at Peak Craft', slug: 'arcane-summary', description: 'A breakdown of style, pacing, and emotional design.', date: '2025-08-29', category: 'Series', tags: ['animation', 'worldbuilding'], readingTime: '5 min', cover: 'from-fuchsia-500/30 to-sky-500/20', kind: 'series-summary', universe: 'personal', body: `${paragraph}` },

  { title: 'Why Frieren’s Quiet Pacing Hits So Hard', slug: 'frieren-blog', description: 'On atmosphere, restraint, and long-form emotional design.', date: '2026-01-01', category: 'Anime Blog', tags: ['frieren', 'analysis'], readingTime: '4 min', cover: 'from-violet-500/35 to-fuchsia-500/20', kind: 'anime-blog', universe: 'personal', body: `${paragraph}` },
  { title: 'AOT Finale Reflections: Narrative Risk and Payoff', slug: 'aot-blog', description: 'A balanced look at audience expectations and intent.', date: '2025-12-12', category: 'Anime Blog', tags: ['aot', 'analysis'], readingTime: '4 min', cover: 'from-rose-500/30 to-purple-500/20', kind: 'anime-blog', universe: 'personal', body: `${paragraph}` },
  { title: 'Severance Season Review: Design as Story Device', slug: 'severance-blog', description: 'How visual language amplifies psychological stakes.', date: '2025-11-03', category: 'Series Blog', tags: ['severance', 'cinematography'], readingTime: '4 min', cover: 'from-indigo-500/30 to-purple-500/20', kind: 'series-blog', universe: 'personal', body: `${paragraph}` },
  { title: 'Dark Rewatch Notes: Causality Without Chaos', slug: 'dark-blog', description: 'What makes complex timelines still emotionally coherent.', date: '2025-10-04', category: 'Series Blog', tags: ['dark', 'narrative'], readingTime: '4 min', cover: 'from-blue-500/30 to-fuchsia-500/20', kind: 'series-blog', universe: 'personal', body: `${paragraph}` }
];
