import { ContentRecord } from './types';

const now = '2026-01-10T00:00:00.000Z';

const body = (topic: string) => `# ${topic}\n\nModern teams need systems, not one-off effort.\n\n## Core ideas\n- Build clarity with principles\n- Ship in repeatable loops\n- Measure outcomes over activity\n\n## Implementation notes\n\`\`\`ts\nconst plan = ['scope', 'ship', 'review'];\n\`\`\`\n\n![Architecture sketch](https://images.unsplash.com/photo-1518770660439-4636190af475?w=1200&q=80&auto=format&fit=crop)\n\n> Callout: Excellence is mostly operational discipline.\n`;

export const seedContent: ContentRecord[] = [
  {
    id: 'p1', slug: 'zero-trust-practice', title: 'Zero Trust in Practice', excerpt: 'Operationalizing least privilege and continuous verification.', body: body('Zero Trust in Practice'), contentType: 'professional_blog', universe: 'professional', category: 'Security Architecture', tags: ['zero-trust', 'iam'], status: 'published', publishedAt: '2026-01-03T00:00:00.000Z', createdAt: now, updatedAt: now, authorName: 'Arharif', coverImageUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1600&q=80&auto=format&fit=crop', videoUrl: 'https://www.youtube.com/embed/9B9wNf18W7s'
  },
  { id: 'p2', slug: 'cloud-security-fundamentals', title: 'Cloud Security Fundamentals', excerpt: 'Practical controls for cloud-native orgs.', body: body('Cloud Security Fundamentals'), contentType: 'professional_blog', universe: 'professional', category: 'Cloud Security', tags: ['cloud', 'cnapp'], status: 'published', publishedAt: '2025-12-02T00:00:00.000Z', createdAt: now, updatedAt: now, authorName: 'Arharif' },
  { id: 'p3', slug: 'iam-at-scale', title: 'Identity and Access Management at Scale', excerpt: 'Identity as the control plane.', body: body('IAM at Scale'), contentType: 'professional_blog', universe: 'professional', category: 'Identity', tags: ['iam', 'sso'], status: 'published', publishedAt: '2025-11-02T00:00:00.000Z', createdAt: now, updatedAt: now, authorName: 'Arharif' },
  { id: 'p4', slug: 'soc-detection-engineering', title: 'SOC Detection Engineering Blueprint', excerpt: 'Designing high-signal detections.', body: body('SOC Detection Engineering'), contentType: 'professional_blog', universe: 'professional', category: 'SOC', tags: ['soc', 'siem'], status: 'published', publishedAt: '2025-10-15T00:00:00.000Z', createdAt: now, updatedAt: now, authorName: 'Arharif' },

  { id: 'b1', slug: 'atomic-habits-summary', title: 'Atomic Habits Summary', excerpt: 'Systems over goals.', body: body('Atomic Habits Summary'), contentType: 'book_summary', universe: 'personal', category: 'Books', tags: ['habits', 'growth'], status: 'published', publishedAt: '2025-12-18T00:00:00.000Z', createdAt: now, updatedAt: now, authorName: 'Arharif' },
  { id: 'b2', slug: 'deep-work-summary', title: 'Deep Work Summary', excerpt: 'Focus as leverage.', body: body('Deep Work Summary'), contentType: 'book_summary', universe: 'personal', category: 'Books', tags: ['focus', 'career'], status: 'published', publishedAt: '2025-11-01T00:00:00.000Z', createdAt: now, updatedAt: now, authorName: 'Arharif' },
  { id: 'a1', slug: 'frieren-summary', title: 'Frieren Summary', excerpt: 'Time, memory, and emotional pacing.', body: body('Frieren Summary'), contentType: 'anime_summary', universe: 'personal', category: 'Anime', tags: ['fantasy', 'storytelling'], status: 'published', publishedAt: '2025-10-05T00:00:00.000Z', createdAt: now, updatedAt: now, authorName: 'Arharif' },
  { id: 'a2', slug: 'aot-analysis', title: 'Attack on Titan Analysis', excerpt: 'Freedom and cyclical conflict.', body: body('Attack on Titan Analysis'), contentType: 'anime_blog', universe: 'personal', category: 'Anime Blog', tags: ['aot', 'analysis'], status: 'published', publishedAt: '2025-09-15T00:00:00.000Z', createdAt: now, updatedAt: now, authorName: 'Arharif' },
  { id: 's1', slug: 'dark-series-summary', title: 'Dark Series Summary', excerpt: 'Complex timelines with emotional coherence.', body: body('Dark Series Summary'), contentType: 'series_summary', universe: 'personal', category: 'Series', tags: ['dark', 'sci-fi'], status: 'published', publishedAt: '2025-08-10T00:00:00.000Z', createdAt: now, updatedAt: now, authorName: 'Arharif' },
  { id: 's2', slug: 'severance-review', title: 'Severance Season Review', excerpt: 'Design language as narrative force.', body: body('Severance Review'), contentType: 'series_blog', universe: 'personal', category: 'Series Blog', tags: ['severance', 'review'], status: 'published', publishedAt: '2025-07-12T00:00:00.000Z', createdAt: now, updatedAt: now, authorName: 'Arharif' }
];
